apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: release-control-plane-state
  namespace: release-control-plane
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
