#ifndef NEBULA_CRYPTO_MBEDTLS_PRIVATE_PREFIX_H
#define NEBULA_CRYPTO_MBEDTLS_PRIVATE_PREFIX_H

/*
 * nebula-crypto vendors a tiny mbedTLS AEAD slice. Prefix its exported C
 * symbols so applications can link nebula-crypto and nebula-tls together.
 */
#define mbedtls_platform_zeroize nebula_crypto_mbedtls_platform_zeroize
#define mbedtls_zeroize_and_free nebula_crypto_mbedtls_zeroize_and_free

#define mbedtls_ct_zero nebula_crypto_mbedtls_ct_zero
#define mbedtls_ct_memcmp nebula_crypto_mbedtls_ct_memcmp
#define mbedtls_ct_memcmp_partial nebula_crypto_mbedtls_ct_memcmp_partial
#define mbedtls_ct_memmove_left nebula_crypto_mbedtls_ct_memmove_left
#define mbedtls_ct_memcpy_if nebula_crypto_mbedtls_ct_memcpy_if
#define mbedtls_ct_memcpy_offset nebula_crypto_mbedtls_ct_memcpy_offset
#define mbedtls_ct_zeroize_if nebula_crypto_mbedtls_ct_zeroize_if

#define mbedtls_chacha20_init nebula_crypto_mbedtls_chacha20_init
#define mbedtls_chacha20_free nebula_crypto_mbedtls_chacha20_free
#define mbedtls_chacha20_setkey nebula_crypto_mbedtls_chacha20_setkey
#define mbedtls_chacha20_starts nebula_crypto_mbedtls_chacha20_starts
#define mbedtls_chacha20_update nebula_crypto_mbedtls_chacha20_update
#define mbedtls_chacha20_crypt nebula_crypto_mbedtls_chacha20_crypt
#define mbedtls_chacha20_self_test nebula_crypto_mbedtls_chacha20_self_test

#define mbedtls_poly1305_init nebula_crypto_mbedtls_poly1305_init
#define mbedtls_poly1305_free nebula_crypto_mbedtls_poly1305_free
#define mbedtls_poly1305_starts nebula_crypto_mbedtls_poly1305_starts
#define mbedtls_poly1305_update nebula_crypto_mbedtls_poly1305_update
#define mbedtls_poly1305_finish nebula_crypto_mbedtls_poly1305_finish
#define mbedtls_poly1305_mac nebula_crypto_mbedtls_poly1305_mac
#define mbedtls_poly1305_self_test nebula_crypto_mbedtls_poly1305_self_test

#define mbedtls_chachapoly_init nebula_crypto_mbedtls_chachapoly_init
#define mbedtls_chachapoly_free nebula_crypto_mbedtls_chachapoly_free
#define mbedtls_chachapoly_setkey nebula_crypto_mbedtls_chachapoly_setkey
#define mbedtls_chachapoly_starts nebula_crypto_mbedtls_chachapoly_starts
#define mbedtls_chachapoly_update_aad nebula_crypto_mbedtls_chachapoly_update_aad
#define mbedtls_chachapoly_update nebula_crypto_mbedtls_chachapoly_update
#define mbedtls_chachapoly_finish nebula_crypto_mbedtls_chachapoly_finish
#define mbedtls_chachapoly_encrypt_and_tag nebula_crypto_mbedtls_chachapoly_encrypt_and_tag
#define mbedtls_chachapoly_auth_decrypt nebula_crypto_mbedtls_chachapoly_auth_decrypt
#define mbedtls_chachapoly_self_test nebula_crypto_mbedtls_chachapoly_self_test

#endif
