#!/usr/bin/env bash
# Single source of truth for the contract-suite baseline number that release
# docs cite. Release numbers MUST be generated by this script, never hand-typed
# — three release documents once disagreed (287 vs 487) because the figure was
# edited by hand. Run this and paste the emitted line.
#
# Usage: scripts/contract_baseline.sh [--suite all|check|run|...] [--binary PATH]
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

suite="all"
binary="$repo_root/build/nebula"
while [ "$#" -gt 0 ]; do
  case "$1" in
    --suite) suite="$2"; shift 2 ;;
    --binary) binary="$2"; shift 2 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

if [ ! -x "$binary" ]; then
  echo "nebula binary not found at $binary (build first: cmake --build build)" >&2
  exit 1
fi

summary="$(python3 "$repo_root/tests/run.py" --suite "$suite" --report text --binary "$binary" \
  | grep -E '^cases:' | tail -1)"

cases="$(printf '%s' "$summary"   | sed -E 's/.*cases:[[:space:]]*([0-9]+).*/\1/')"
passed="$(printf '%s' "$summary"  | sed -E 's/.*passed:[[:space:]]*([0-9]+).*/\1/')"
failed="$(printf '%s' "$summary"  | sed -E 's/.*failed:[[:space:]]*([0-9]+).*/\1/')"

echo "Contract suite baseline (suite=$suite): ${passed}/${cases} passed, ${failed} failed"
[ "$failed" = "0" ]
